gateways:
  dev:
    connection:
      type: duckdb
      concurrent_tasks: 1
      register_comments: true
      pre_ping: false
      pretty_sql: false
      database: jaffle_shop.duckdb
      extensions: []
      connector_config: {}
      secrets: []
      filesystems: []
    state_schema: sqlmesh
    variables: {}
  prod:
    connection:
      type: duckdb
      database: jaffle_shop.duckdb
    state_schema: sqlmesh
model_defaults:
  dialect: duckdb
variables:
  __dbt_packages__: {}
  __dbt_project_name__: jaffle_shop
linter:
  enabled: true
  rules:
    - ambiguousorinvalidcolumn
    - invalidselectstarexpansion
  warn_rules: 
    - noselectstar
cicd_bot:
  type: github
  invalidate_environment_after_deploy: false
  enable_deploy_command: true
  merge_method: squash
  command_namespace: "#SQLMesh"
  auto_categorize_changes:
    external: full
    python: full
    sql: full
    seed: full
  default_pr_start: "1 week ago"
  skip_pr_backfill: true
  run_on_deploy_to_prod: false
  prod_branch_name: production

