name: SQLMesh Plan Bot

on:
  push:
    branches:
      - main
      - dev

jobs:
  sqlmesh:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install SQLMesh + Dependencies
        run: pip install -r requirements.txt
        working-directory: sqlmesh-jaffle-shop
      - name: Run SQLMesh Plan
        run: sqlmesh plan
        working-directory: sqlmesh-jaffle-shop

      # Optionally, auto-apply the plan
      # - name: Apply SQLMesh Plan
      #   run: sqlmesh apply